name: Tests

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Install Rust
        run: rustup update stable
      - name: Run tests
        run: cargo test --workspace
